#!/usr/bin/env bash
# Boot the ephemeral regression stack from nothing (spec §3, milestone M1).
#
#   HEROKU_API_KEY=... stack/scripts/bootstrap.sh
#
# The bootstrap sequence is registry login → pull → generate the Postgres certificate and
# the throwaway SSO keypair → start Postgres and SSO → one-off `create-service-user odb` to
# mint the service JWT that odb/itc/obscalc share → start the rest → wait for readiness.
# It is idempotent: re-running against a live stack re-checks readiness without resetting
# anything (use stack/scripts/down.sh for that).
#
# Useful switches:
#   SKIP_PULL=1          use whatever images are already local
#   SKIP_HOSTS=1         do not touch /etc/hosts
#   FORCE=1              regenerate certificate and keypair
#   ODB_OTEL_ENDPOINT=…  ship ODB traces to Grafana Cloud (spec §7); requires ODB_OTEL_KEY
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

require_cmd docker git curl node

log "bootstrapping the ephemeral stack on domain $GPP_TEST_DOMAIN"

# ---------------------------------------------------------------------------
# 1. Secrets and inputs that exist only for this run
# ---------------------------------------------------------------------------
bash "$STACK_DIR/scripts/gen-certs.sh"
bash "$STACK_DIR/scripts/gen-sso-keys.sh"
bash "$STACK_DIR/scripts/fetch-lucuma-apps.sh"

# Everything below (and any later `docker compose` call) reads the stack's environment from
# this file. The armoured keys are read from disk rather than inlined so the file stays
# diffable and short.
cat > "$GENERATED_ENV" <<EOF
# Generated by stack/scripts/bootstrap.sh — safe to delete, safe to re-source.
export GPP_TEST_DOMAIN="$GPP_TEST_DOMAIN"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-odbattr}"
export LUCUMA_APPS_DIR="${LUCUMA_APPS_DIR:-$STACK_DIR/.cache/lucuma-apps}"
export GPG_SSO_PUBLIC_KEY="\$(cat "$STACK_DIR/keys/sso-public.asc")"
export GPG_SSO_PRIVATE_KEY="\$(cat "$STACK_DIR/keys/sso-private.asc")"
export GPG_SSO_PASSPHRASE="\$(cat "$STACK_DIR/keys/passphrase")"
export NODE_EXTRA_CA_CERTS="$STACK_DIR/certs/caddy-root.crt"
EOF

# OpenTelemetry is opt-in: a non-local ODB_ENVIRONMENT makes both OTel variables mandatory,
# so the stack only leaves `local` when an endpoint was actually supplied (spec §7).
if [[ -n "${ODB_OTEL_ENDPOINT:-}" ]]; then
  [[ -n "${ODB_OTEL_KEY:-}" ]] || die "ODB_OTEL_ENDPOINT is set but ODB_OTEL_KEY is not"
  cat >> "$GENERATED_ENV" <<EOF
export ODB_ENVIRONMENT="${ODB_ENVIRONMENT:-dev}"
export ODB_OTEL_ENDPOINT="$ODB_OTEL_ENDPOINT"
export ODB_OTEL_KEY="$ODB_OTEL_KEY"
export OTEL_ENVIRONMENT="${OTEL_ENVIRONMENT:-ephemeral}"
EOF
  log "OpenTelemetry enabled (environment=${OTEL_ENVIRONMENT:-ephemeral})"
else
  log "OpenTelemetry disabled (set ODB_OTEL_ENDPOINT and ODB_OTEL_KEY to enable)"
fi

load_generated_env

[[ -n "${SKIP_HOSTS:-}" ]] || bash "$STACK_DIR/scripts/hosts.sh"

# ---------------------------------------------------------------------------
# 2. Images — `:latest` from the -dev Heroku apps, i.e. latest main
# ---------------------------------------------------------------------------
if [[ -z "${SKIP_PULL:-}" ]]; then
  if [[ -n "${HEROKU_API_KEY:-}" ]]; then
    log "logging in to registry.heroku.com"
    echo "$HEROKU_API_KEY" | docker login registry.heroku.com -u _ --password-stdin >/dev/null
  else
    warn "HEROKU_API_KEY is not set — the lucuma images can only be pulled with it."
    warn "If they are already local, re-run with SKIP_PULL=1. The documented fallback is"
    warn "building them yourself with sbt docker:publishLocal (see README)."
  fi
  log "pulling images"
  compose pull --quiet
fi

# ---------------------------------------------------------------------------
# 3. Phase one: Postgres, then SSO (which migrates its own database)
# ---------------------------------------------------------------------------
log "starting postgres and sso (sso migrates the lucuma-sso database on boot)"
compose up --detach --wait postgres
compose up --detach sso

# ---------------------------------------------------------------------------
# 4. The service JWT odb, itc and obscalc share
#
# This doubles as the readiness gate for SSO: the subcommand needs a migrated SSO database
# and the signing key, so retrying it until a JWT appears is both simpler and stricter than
# probing an HTTP endpoint from inside the network.
#
# Always minted fresh, never inherited. A JWT from a previous stack is signed by that stack's
# keypair, and this one will not verify it — a mismatch that surfaces minutes later as
# `java.security.SignatureException: Bad signature length` deep inside obscalc, with nothing
# pointing back at the token. `create-service-user` is idempotent for a given service name
# ("if it is lost you may re-run this command"), so re-minting costs seconds and removes the
# whole failure mode.
# ---------------------------------------------------------------------------
unset ODB_SERVICE_JWT

log "minting the ODB service JWT (create-service-user odb)"
attempts="${SERVICE_USER_ATTEMPTS:-40}"
for attempt in $(seq 1 "$attempts"); do
  # `docker exec` on the running sso rather than `compose run`, so the token is minted by the
  # very container the stack is using — same keypair, by construction.
  service_user_output="$(compose exec -T sso \
    /opt/docker/bin/lucuma-sso-service create-service-user odb 2>&1)" || true

  # The subcommand prints a JWT among its log lines; take the last JWT-shaped token.
  # `|| true` matters: no match makes grep exit 1, and with `set -e -o pipefail` that
  # would abort the bootstrap on the first attempt instead of retrying.
  ODB_SERVICE_JWT="$(printf '%s\n' "$service_user_output" \
    | grep -oE 'eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+' \
    | tail -1 || true)"

  # Scraping stdout is inherently loose, so check we grabbed the right thing: a service-user
  # token whose signature was made by the key this stack is running.
  if [[ -n "$ODB_SERVICE_JWT" ]] \
    && node "$REPO_DIR/tools/check-service-jwt.js" "$ODB_SERVICE_JWT" \
         --public-key "$STACK_DIR/keys/sso-public.asc"; then
    break
  fi

  if [[ "$attempt" -eq "$attempts" ]]; then
    printf '%s\n' "$service_user_output" >&2
    warn "last 40 lines of the sso log:"
    compose logs --tail 40 sso >&2 || true
    die "could not mint a usable service JWT after $attempts attempts (output above)"
  fi
  if [[ $(( attempt % 6 )) -eq 0 ]]; then
    log "still waiting for SSO (attempt $attempt/$attempts)"
  fi
  sleep 5
done

echo "export ODB_SERVICE_JWT=\"$ODB_SERVICE_JWT\"" >> "$GENERATED_ENV"
export ODB_SERVICE_JWT
log "service JWT minted (${#ODB_SERVICE_JWT} chars)"

# ---------------------------------------------------------------------------
# 5. Explore's runtime configuration, then everything else
# ---------------------------------------------------------------------------
log "writing Explore's environments.conf.json"
EXPLORE_ORIGIN="${EXPLORE_ORIGIN:-explore-gemini-dev.web.app}" \
  node "$REPO_DIR/tools/write-environments-conf.js" \
  "$STACK_DIR/.cache/explore/environments.conf.json"

log "starting odb, itc, obscalc, hasura and caddy"
compose up --detach

bash "$STACK_DIR/scripts/wait-for-ready.sh"
bash "$STACK_DIR/scripts/trust-ca.sh" >/dev/null
bash "$STACK_DIR/scripts/record-images.sh" "$REPO_DIR/out/images.json"

log "stack is up:"
log "  Explore  https://explore.$GPP_TEST_DOMAIN"
log "  ODB      https://odb.$GPP_TEST_DOMAIN/odb"
log "  SSO      https://sso.$GPP_TEST_DOMAIN"
log "  prefs    https://prefs.$GPP_TEST_DOMAIN/v1/graphql"
log ""
log "for a shell that can talk to it:  source stack/.env.generated"
log "then verify the GraphQL contract:  npm run verify:operations"
