#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

# Phase 2 of research/aws-load-target-options.md: the compose stack on one EC2
# instance, driven by k6 from a second one, by hand, to find out whether AWS
# numbers tell us anything Heroku's cannot. Everything is tagged odbattr:loadtest=1
# — the discriminator a phase-3 IAM policy would condition on.
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"
mkdir -p out
ENV_FILE="out/aws-loadtest.env"   # gitignored, and separate from the repo's own .env

TAG_KEY="odbattr:loadtest"
TAG_VALUE="1"
SPEC='ResourceType=instance,Tags=[{Key=Name,Value=REPLACED},{Key='"$TAG_KEY"',Value='"$TAG_VALUE"'}]'

# awsx — the AWS CLI with this run's region and profile already applied.
awsx() {
  # shellcheck disable=SC2086
  aws --region "$AWS_REGION" ${AWS_PROFILE:+--profile "$AWS_PROFILE"} "$@"
}

# ssh_to / rsync_to — the target and generator are reached the same way.
ssh_to() {
  local host="$1"; shift
  ssh -i "$PEM_PATH" -o StrictHostKeyChecking=accept-new -o ConnectTimeout=10 \
      -o ServerAliveInterval=30 "ubuntu@$host" "$@"
}
rsync_to() {
  local host="$1"
  rsync -az --delete \
    -e "ssh -i $PEM_PATH -o StrictHostKeyChecking=accept-new" \
    --exclude node_modules --exclude .direnv --exclude stack/.cache \
    --exclude out --exclude test-results --exclude playwright-report \
    "$REPO_DIR/" "ubuntu@$host:~/odbattr/"
}

banner "GPP load test on AWS — first manual run"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — the AWS identity you are about to spend money with"
say "This wizard launches two EC2 instances, runs a 40-minute load profile"
say "against them, and stops them again. Roughly \$1.16 for the run."
printf '\n'

command -v aws >/dev/null 2>&1 || { warn "the AWS CLI is not installed — https://aws.amazon.com/cli/"; exit 1; }
command -v rsync >/dev/null 2>&1 || { warn "rsync is required (it ships with macOS)"; exit 1; }

ask AWS_REGION  "AWS region [us-east-1]:"
[[ -n "$AWS_REGION" ]] || AWS_REGION="us-east-1"
ask AWS_PROFILE "AWS CLI profile (blank for the default):"

CALLER_ARN="$(awsx sts get-caller-identity --query Arn --output text 2>/dev/null || true)"
if [[ -z "$CALLER_ARN" ]]; then
  warn "could not call sts:GetCallerIdentity — check your credentials for this profile"
  exit 1
fi
ACCOUNT_ID="$(awsx sts get-caller-identity --query Account --output text)"
say ""
say "account:  $ACCOUNT_ID"
say "identity: $CALLER_ARN"
say ""

# The root user cannot be constrained by IAM at all, which is exactly the control
# that made a separate AWS account the safer option. Refuse rather than warn.
if [[ "$CALLER_ARN" == *":root" ]]; then
  warn "That is the account ROOT user."
  say "IAM policies cannot constrain root, so the tag-scoped rail this tooling is"
  say "built around would have nothing to bite on — and root can close the account."
  say ""
  step "Enable MFA on root, then IAM → Users → create 'odbattr-loadtest'."
  step "Attach AdministratorAccess, create a CLI access key."
  step "aws configure --profile odbattr, then re-run this wizard."
  exit 1
fi

if ! confirm "Is $ACCOUNT_ID the dedicated TEST account (no production in it)?"; then
  say "Stopping. Point this at the test account and re-run."
  exit 1
fi
write_env AWS_REGION "$AWS_REGION"
write_env AWS_PROFILE "$AWS_PROFILE"
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Key pair and security group"
say "SSH is opened to your current public IP only; the target's 443 is reachable"
say "only from inside the group, i.e. from the generator."
printf '\n'

ask KEY_NAME "EC2 key pair name [odbattr-loadtest]:"
[[ -n "$KEY_NAME" ]] || KEY_NAME="odbattr-loadtest"
PEM_PATH="$HOME/.ssh/$KEY_NAME.pem"

if awsx ec2 describe-key-pairs --key-names "$KEY_NAME" >/dev/null 2>&1; then
  say "key pair $KEY_NAME already exists in $AWS_REGION"
  [[ -f "$PEM_PATH" ]] || { warn "but $PEM_PATH is missing — delete the key pair in EC2 and re-run"; exit 1; }
else
  awsx ec2 create-key-pair --key-name "$KEY_NAME" \
    --query KeyMaterial --output text > "$PEM_PATH"
  chmod 600 "$PEM_PATH"
  say "created $KEY_NAME → $PEM_PATH"
fi

VPC_ID="$(awsx ec2 describe-vpcs --filters Name=is-default,Values=true \
  --query 'Vpcs[0].VpcId' --output text)"
[[ "$VPC_ID" != "None" ]] || { warn "no default VPC in $AWS_REGION — create one, or edit this script"; exit 1; }
say "VPC: $VPC_ID (default)"

# Both instances must land in the SAME availability zone. Cross-AZ traffic is billed
# per GB each way, and a 200-VU run moves a few GB between generator and target — so
# leaving the AZ to chance would put a data-transfer charge on the run, and add a
# network hop to the latency being measured.
SUBNET_ID="$(awsx ec2 describe-subnets --filters Name=vpc-id,Values="$VPC_ID" \
  Name=default-for-az,Values=true --query 'Subnets[0].SubnetId' --output text)"
SUBNET_AZ="$(awsx ec2 describe-subnets --subnet-ids "$SUBNET_ID" \
  --query 'Subnets[0].AvailabilityZone' --output text)"
say "subnet: $SUBNET_ID ($SUBNET_AZ) — both instances go here, so the load stays in one AZ"
write_env SUBNET_ID "$SUBNET_ID"

SG_ID="$(awsx ec2 describe-security-groups \
  --filters Name=group-name,Values=odbattr-loadtest Name=vpc-id,Values="$VPC_ID" \
  --query 'SecurityGroups[0].GroupId' --output text 2>/dev/null || echo None)"
if [[ "$SG_ID" == "None" || -z "$SG_ID" ]]; then
  SG_ID="$(awsx ec2 create-security-group --group-name odbattr-loadtest \
    --description "odbattr load test - ephemeral" --vpc-id "$VPC_ID" \
    --query GroupId --output text)"
  awsx ec2 create-tags --resources "$SG_ID" --tags "Key=$TAG_KEY,Value=$TAG_VALUE"
  say "created security group $SG_ID"
fi

MY_IP="$(curl -fsS https://checkip.amazonaws.com | tr -d '[:space:]')"
say "your public IP: $MY_IP"
awsx ec2 authorize-security-group-ingress --group-id "$SG_ID" \
  --protocol tcp --port 22 --cidr "$MY_IP/32" >/dev/null 2>&1 \
  && say "opened SSH from $MY_IP/32" || note "SSH rule already present"
awsx ec2 authorize-security-group-ingress --group-id "$SG_ID" \
  --protocol tcp --port 443 --source-group "$SG_ID" >/dev/null 2>&1 \
  && say "opened 443 within the group" || note "443 rule already present"

write_env KEY_NAME "$KEY_NAME"
write_env SG_ID "$SG_ID"
pause

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Launch the target and the generator"
warn "x86_64 only: the lucuma images are linux/amd64, so a Graviton instance"
note "  would be cheaper and then fail to run them. Keep the defaults unless you"
note "  are deliberately testing another size."
printf '\n'

ask TARGET_TYPE "Target instance type [m7i.4xlarge]:"
[[ -n "$TARGET_TYPE" ]] || TARGET_TYPE="m7i.4xlarge"
ask GEN_TYPE "Generator instance type [c7i.2xlarge]:"
[[ -n "$GEN_TYPE" ]] || GEN_TYPE="c7i.2xlarge"

AMI_ID="$(awsx ssm get-parameters \
  --names /aws/service/canonical/ubuntu/server/24.04/stable/current/amd64/hvm/ebs-gp3/ami-id \
  --query 'Parameters[0].Value' --output text)"
say "Ubuntu 24.04 AMI: $AMI_ID"

launch() {
  local name="$1" type="$2" disk="$3"
  awsx ec2 run-instances \
    --image-id "$AMI_ID" --instance-type "$type" --key-name "$KEY_NAME" \
    --security-group-ids "$SG_ID" --subnet-id "$SUBNET_ID" --count 1 \
    --block-device-mappings "DeviceName=/dev/sda1,Ebs={VolumeSize=$disk,VolumeType=gp3}" \
    --tag-specifications "${SPEC/REPLACED/$name}" \
    --query 'Instances[0].InstanceId' --output text
}

if [[ -z "$(_existing TARGET_ID || true)" ]]; then
  TARGET_ID="$(launch odbattr-target "$TARGET_TYPE" 60)"
  GEN_ID="$(launch odbattr-generator "$GEN_TYPE" 30)"
  say "launched target $TARGET_ID and generator $GEN_ID — waiting for them to run"
  awsx ec2 wait instance-running --instance-ids "$TARGET_ID" "$GEN_ID"
  write_env TARGET_ID "$TARGET_ID"
  write_env GEN_ID "$GEN_ID"
else
  TARGET_ID="$(_existing TARGET_ID)"; GEN_ID="$(_existing GEN_ID)"
  say "reusing $TARGET_ID / $GEN_ID from a previous run"
  awsx ec2 start-instances --instance-ids "$TARGET_ID" "$GEN_ID" >/dev/null 2>&1 || true
  awsx ec2 wait instance-running --instance-ids "$TARGET_ID" "$GEN_ID"
fi

ip_of() { awsx ec2 describe-instances --instance-ids "$1" --query "$2" --output text; }
TARGET_IP="$(ip_of "$TARGET_ID" 'Reservations[0].Instances[0].PublicIpAddress')"
TARGET_PRIVATE_IP="$(ip_of "$TARGET_ID" 'Reservations[0].Instances[0].PrivateIpAddress')"
GEN_IP="$(ip_of "$GEN_ID" 'Reservations[0].Instances[0].PublicIpAddress')"
write_env TARGET_IP "$TARGET_IP"
write_env TARGET_PRIVATE_IP "$TARGET_PRIVATE_IP"
write_env GEN_IP "$GEN_IP"
say "target $TARGET_IP (private $TARGET_PRIVATE_IP) · generator $GEN_IP"
warn "both are billing from now until stage 9."
pause

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Bootstrap the stack on the target"
say "Docker, Node 22, then stack/scripts/bootstrap.sh — the same script the"
say "nightly regression run boots from empty. Pulling ~3.5 GB of images, so"
say "this is the long stage: 8-15 minutes."
printf '\n'

if [[ -n "${HEROKU_API_KEY:-}" ]]; then
  say "using HEROKU_API_KEY from your environment"
else
  say "The images live only in Heroku's registry, so the target needs a key that"
  say "can pull them (read on lucuma-*-dev is enough)."
  ask_secret HEROKU_API_KEY "Heroku API key:"
fi

say "waiting for SSH on $TARGET_IP"
for _ in $(seq 1 30); do
  ssh_to "$TARGET_IP" true >/dev/null 2>&1 && break
  sleep 10
done

say "installing prerequisites"
ssh_to "$TARGET_IP" bash -s <<'REMOTE'
set -euo pipefail
sudo apt-get update -qq
sudo apt-get install -y -qq docker.io docker-compose-v2 git curl gpg jq rsync >/dev/null
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - >/dev/null 2>&1
sudo apt-get install -y -qq nodejs >/dev/null
sudo usermod -aG docker ubuntu
REMOTE

say "syncing the working copy (not a clone — this tests the code you have)"
rsync_to "$TARGET_IP"

# stack/docker-compose.yml ships CI-sized memory limits — odb 2g, postgres 1g, itc 1g,
# obscalc 1g, sso 768m, caddy 256m, hasura 512m — because its day job is booting on a 2-core
# GitHub runner. Left alone on a load target they are what you measure, not the machine.
#
# The shares below come from the 2026-08-27 runs on a 64 GiB m7i.4xlarge, not from a guess:
#
#   at  200 VUs   odb 11.6G  itc 3.0G  obscalc 2.7G  postgres 1.9G  sso 1.2G
#   ramping 1500  odb 23.3G  itc 4.7G  obscalc 3.9G  postgres 2.1G  sso 1.3G  hasura 0.45G
#
# Two OOM kills taught the rest. Run 1 left odb at its 2g default and the kernel killed it 14
# minutes in at ~185 VUs. Run 3 raised every service *except the proxy* — and caddy died at
# its 256m default, taking the whole run with it, because a saturated backend leaves
# connections queued in the proxy and its memory grows with them. Sizing six of seven
# services is the same as sizing none.
#
# These are caps, not reservations: measured total usage was ~36 GiB, so the shares may
# safely sum past what the box could satisfy all at once.
TARGET_MIB="$(awsx ec2 describe-instance-types --instance-types "$TARGET_TYPE" \
  --query 'InstanceTypes[0].MemoryInfo.SizeInMiB' --output text)"
pct() { printf '%sm' "$(( TARGET_MIB * $1 / 100 ))"; }
LIMITS="ODB_MEM_LIMIT=$(pct 40) ITC_MEM_LIMIT=$(pct 10) OBSCALC_MEM_LIMIT=$(pct 8) \
CADDY_MEM_LIMIT=$(pct 8) PG_MEM_LIMIT=$(pct 6) SSO_MEM_LIMIT=$(pct 4) \
HASURA_MEM_LIMIT=$(pct 2) PG_MAX_CONNECTIONS=400"
say "memory limits for ${TARGET_MIB}MiB:"
say "  odb $(pct 40)  itc $(pct 10)  obscalc $(pct 8)  caddy $(pct 8)  postgres $(pct 6)  sso $(pct 4)  hasura $(pct 2)"
note "  Caps rather than reservations. Override any of them in the environment; a target that"
note "  only serves k6 does not need hasura at all (it is Explore's preferences service)."

say "booting the stack"
ssh_to "$TARGET_IP" "HEROKU_API_KEY='$HEROKU_API_KEY' $LIMITS bash -lc 'cd ~/odbattr && sg docker -c \"stack/scripts/bootstrap.sh\"'"
say ""
say "the stack is up and its seven readiness checks passed"
pause

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Prepare the generator"
say "k6 and Node, the same working copy, and /etc/hosts pointing the stack's"
say "names at the target's PRIVATE ip — so the load stays inside the VPC."
printf '\n'

say "waiting for SSH on $GEN_IP"
for _ in $(seq 1 30); do
  ssh_to "$GEN_IP" true >/dev/null 2>&1 && break
  sleep 10
done

ssh_to "$GEN_IP" bash -s <<'REMOTE'
set -euo pipefail
sudo apt-get update -qq
sudo apt-get install -y -qq curl ca-certificates git rsync >/dev/null
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - >/dev/null 2>&1
sudo apt-get install -y -qq nodejs >/dev/null

# k6 from its release tarball rather than the apt repo. The documented apt route imports
# the signing key with `sudo gpg --recv-keys`, which needs a root GPG home (`sudo gpg -k`
# first) and dirmngr — neither present on a minimal cloud image — and then depends on a
# keyserver being reachable. One binary has none of those failure modes.
if ! command -v k6 >/dev/null 2>&1; then
  TAG="$(curl -fsSL https://api.github.com/repos/grafana/k6/releases/latest \
    | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)"
  [ -n "$TAG" ] || { echo "could not resolve the latest k6 release from GitHub" >&2; exit 1; }
  ASSET="k6-${TAG}-linux-amd64"
  curl -fsSL "https://github.com/grafana/k6/releases/download/${TAG}/${ASSET}.tar.gz" \
    | sudo tar -xz -C /usr/local/bin --strip-components=1 "${ASSET}/k6"
fi
k6 version
REMOTE

rsync_to "$GEN_IP"

ssh_to "$GEN_IP" "sudo sed -i '/gpp-test.internal/d' /etc/hosts && \
  echo '$TARGET_PRIVATE_IP odb.gpp-test.internal sso.gpp-test.internal itc.gpp-test.internal explore.gpp-test.internal prefs.gpp-test.internal' \
  | sudo tee -a /etc/hosts >/dev/null"
say "generator resolves the stack at $TARGET_PRIVATE_IP"
pause

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Smoke run — 10 VUs, about two minutes"
say "Proves the whole path before committing 40 minutes: guest auth, the"
say "GraphQL mix, TLS through Caddy, and the target-host guard accepting"
say "*.gpp-test.internal. A failure here is cheap."
printf '\n'

K6_ENV="SUITE=load \
ODB_GRAPHQL_URL=https://odb.gpp-test.internal/odb \
SSO_URL=https://sso.gpp-test.internal"

ssh_to "$GEN_IP" "cd ~/odbattr && $K6_ENV \
  VUS_LOW=5 VUS_HIGH=10 STAGE_1=30s STAGE_2=30s STAGE_3=30s STAGE_4=10s \
  MIN_CHECK_RATE=0.95 k6 run k6/load.js" || {
    warn "the smoke run failed — fix this before the full profile"
    note "  ssh -i $PEM_PATH ubuntu@$GEN_IP    then look at ~/odbattr"
    note "  ssh -i $PEM_PATH ubuntu@$TARGET_IP then: cd odbattr && docker compose logs odb"
    exit 1
  }
say ""
say "plumbing confirmed"
pause

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "The full profile — 0→50→200 VUs, ~40 minutes"
say "OTEL_ENVIRONMENT=aws-loadtest tags the summary as its own environment, so"
say "these numbers never blend into a Heroku baseline."
printf '\n'

GRAFANA_ARGS=""
if confirm "Stream metrics to Grafana Cloud live?"; then
  ask       GC_PROM_RW_URL      "Prometheus remote-write URL:"
  ask       GC_PROM_INSTANCE_ID "Instance ID (username):"
  ask_secret GC_PROM_TOKEN      "Access policy token:"
  write_env GC_PROM_RW_URL "$GC_PROM_RW_URL"
  write_env GC_PROM_INSTANCE_ID "$GC_PROM_INSTANCE_ID"
  GRAFANA_ARGS="-o experimental-prometheus-rw"
  K6_ENV="$K6_ENV \
K6_PROMETHEUS_RW_SERVER_URL='$GC_PROM_RW_URL' \
K6_PROMETHEUS_RW_USERNAME='$GC_PROM_INSTANCE_ID' \
K6_PROMETHEUS_RW_PASSWORD='$GC_PROM_TOKEN' \
K6_PROMETHEUS_RW_TREND_STATS='avg,p(95),p(99)'"
fi

confirm "Start the 40-minute run now?" || { say "Stopping here — nothing torn down."; exit 0; }

# Detached, so a dropped SSH connection or a sleeping laptop cannot lose the run.
ssh_to "$GEN_IP" "cd ~/odbattr && mkdir -p out && \
  nohup env $K6_ENV OTEL_ENVIRONMENT=aws-loadtest \
  k6 run $GRAFANA_ARGS --summary-export out/k6-summary.json k6/load.js \
  > out/k6-run.log 2>&1 & sleep 5" || true
say "running detached on the generator; following the log."
note "Ctrl-C stops the tail, not the run. Re-attach with:"
note "  ssh -i $PEM_PATH ubuntu@$GEN_IP 'tail -f odbattr/out/k6-run.log'"
printf '\n'
ssh_to "$GEN_IP" "tail -f --pid=\$(pgrep -f 'k6 run' | head -1) odbattr/out/k6-run.log" || true
pause "Run finished — press Enter to collect the results"

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Collect the numbers"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
scp -i "$PEM_PATH" -o StrictHostKeyChecking=accept-new \
  "ubuntu@$GEN_IP:~/odbattr/out/k6-summary.json" "out/k6-aws-$STAMP.json"
scp -i "$PEM_PATH" -o StrictHostKeyChecking=accept-new \
  "ubuntu@$GEN_IP:~/odbattr/out/k6-run.log" "out/k6-aws-$STAMP.log" 2>/dev/null || true
say "saved out/k6-aws-$STAMP.json"
printf '\n'

node --input-type=commonjs -e '
const s = require("./out/k6-aws-'"$STAMP"'.json");
const m = s.metrics ?? {};
const p95 = (k) => m[k]?.["p(95)"]?.toFixed(1) ?? "—";
console.log("  target        : '"$TARGET_TYPE"' (generator '"$GEN_TYPE"')");
console.log("  http p95      :", p95("http_req_duration"), "ms");
console.log("  odb read  p95 :", p95("odb_read_duration"), "ms");
console.log("  odb write p95 :", p95("odb_write_duration"), "ms");
const failed = m.http_req_failed?.value;
if (failed !== undefined) console.log("  request errors:", (failed * 100).toFixed(2) + "%");
const pass = m.gpp_scenario_pass;
if (pass) console.log("  scenario pass :", (pass.value * 100).toFixed(1) + "%");
' || warn "could not summarise — the raw JSON is in out/"

printf '\n'
note "No Heroku baseline exists yet (M4 unprovisioned), so this is an absolute"
note "number on known hardware rather than a comparison. Keep the JSON: it is the"
note "first data point, and stage 3's instance types are what produced it."
pause

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Tear down — the stage that decides the bill"
warn "Two instances are still running: $TARGET_ID and $GEN_ID"
say ""
say "  stop      keeps the disks (a few \$/month), boots again in minutes"
say "  terminate leaves nothing behind at all"
say "  leave     they keep billing by the hour"
say ""
ask TEARDOWN "stop / terminate / leave [stop]:"
[[ -n "$TEARDOWN" ]] || TEARDOWN="stop"

case "$TEARDOWN" in
  terminate)
    if confirm "Terminate both instances? The stack and its data are gone for good."; then
      awsx ec2 terminate-instances --instance-ids "$TARGET_ID" "$GEN_ID" >/dev/null
      say "terminating. The key pair and security group remain for next time."
      # Nothing to reuse, so drop the ids rather than offer them on a re-run.
      write_env TARGET_ID ""
      write_env GEN_ID ""
    else
      warn "left running — they are still billing"
    fi
    ;;
  leave)
    warn "left running — they are still billing"
    note "  aws ec2 stop-instances --instance-ids $TARGET_ID $GEN_ID --region $AWS_REGION"
    ;;
  *)
    awsx ec2 stop-instances --instance-ids "$TARGET_ID" "$GEN_ID" >/dev/null
    say "stopping both. Re-run this wizard to bring the same pair back up."
    ;;
esac

finish
