#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 && -z "${AUTO:-}" ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  if [[ -n "${AUTO:-}" ]]; then
    printf '  %s%s%s\n' "$DIM" "${1:-—}" "$RESET"
    return 0
  fi
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" [VAR] [auto-default] — y/N gate; returns success on yes. Under AUTO the
# answer is $VAR when given (y/1/true = yes), else the auto-default (n unless stated).
confirm() {
  local reply="" var="${2:-}" fallback="${3:-n}"
  if [[ -n "${AUTO:-}" ]]; then
    reply="$fallback"
    if [[ -n "$var" && -n "${!var:-}" ]]; then reply="${!var}"; fi
    printf '  %s? %s%s → %s %s(AUTO%s)%s\n' "$YELLOW" "$1" "$RESET" "$reply" "$DIM" "${var:+, $var}" "$RESET"
    [[ "$reply" =~ ^([Yy]|1|true) ]]
    return
  fi
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "${AUTO:-}" ]]; then
    # An environment variable of the same name overrides; else the saved value; else the
    # caller's default applies to an empty answer.
    input="${!key:-}"
    [[ -n "$input" ]] || input="$current"
    printf '  %s%s%s → %s %s(AUTO)%s\n' "$BOLD" "$prompt" "$RESET" "${input:-<default>}" "$DIM" "$RESET"
    printf -v "$key" '%s' "$input"
    return 0
  fi
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "${AUTO:-}" ]]; then
    input="${!key:-}"
    [[ -n "$input" ]] || input="$current"
    [[ -n "$input" ]] || { warn "AUTO: $key is not set and nothing is saved for it"; exit 1; }
    printf '  %s%s%s → %s(AUTO, from the environment)%s\n' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
    printf -v "$key" '%s' "$input"
    return 0
  fi
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=12

# The compose stack on one EC2 instance, driven by k6 from a second one, by hand
# (research/aws-load-target-options.md phase 2) — under NOIRLab's launch procedure for the
# shared account 384445651298:
#
#   - us-west-2, launched only through the launch template IT maintains for GPP
#     (NOIRLab-Software-GPP: private subnet nl-vpc-private-us-west-2a, no public IP, the
#     HTTP/HTTPS/SSH security groups, the SSM instance profile, Department=Software tags);
#   - access only through AWS SSM — ssh and rsync tunnel through `ssm start-session`, by
#     instance id;
#   - an Ubuntu LTS image, which ships the SSM agent (the template's own image is arm64
#     Amazon Linux, and the lucuma images are amd64-only, so the image is overridden).
#
# The account is shared with production-adjacent NOIRLab infrastructure, and the procedure
# lets this user stop and terminate *any* Department=Software instance. So this wizard only
# ever starts, stops or terminates instance ids it launched itself, and re-checks each one's
# gpp-tests:loadtest=1 tag and Name before doing so — see owned_or_die.
#
# Verified by hand on 2026-10-02 (a t3.micro through the template: SSM online in ~18s, ssh
# and rsync over SSM, egress to GitHub and both registries through the NAT).
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"
mkdir -p out
# Gitignored, and separate from the repo's own .env. Named for the region so the values
# saved by the first (us-east-1, public-IP) runs are never offered back.
ENV_FILE="out/aws-loadtest-us-west-2.env"
KNOWN_HOSTS="out/aws-known_hosts"

TAG_KEY="gpp-tests:loadtest"
TAG_VALUE="1"
NAMES_WE_LAUNCH="gpp-tests-target gpp-tests-generator"

# awsx — the AWS CLI with this run's region and profile already applied.
awsx() {
  # shellcheck disable=SC2086
  aws --region "$AWS_REGION" ${AWS_PROFILE:+--profile "$AWS_PROFILE"} "$@"
}

# ssh over SSM: no public IPs exist, so every connection is tunnelled through
# `ssm start-session` (AWS-StartSSHSession) to the instance id, with the key pair for login.
# One generated ssh config carries it, so ssh, scp and rsync all read the same settings —
# rsync's -e does not reliably preserve a quoted ProxyCommand.
SSH_CONFIG="out/aws-ssh_config"
write_ssh_config() {
  cat > "$SSH_CONFIG" <<CONFIG
Host i-*
  User ubuntu
  IdentityFile $PEM_PATH
  IdentitiesOnly yes
  ProxyCommand aws --region $AWS_REGION ${AWS_PROFILE:+--profile $AWS_PROFILE} ssm start-session --target %h --document-name AWS-StartSSHSession --parameters portNumber=%p
  StrictHostKeyChecking accept-new
  UserKnownHostsFile $REPO_DIR/$KNOWN_HOSTS
  ConnectTimeout 30
  ServerAliveInterval 30
CONFIG
}
ssh_to()   { local id="$1"; shift; ssh -F "$SSH_CONFIG" "$id" "$@"; }
scp_from() { scp -F "$SSH_CONFIG" "$1:$2" "$3"; }
# stack/certs and stack/keys are each host's own: bootstrap mints them there, and Caddy's
# root differs per stack, so the laptop's copies must not travel (the laptop's truststore
# on the target made every proposal submission answer 500, 2026-10-07). An exclude also
# protects the remote copy from --delete.
rsync_to() {
  rsync -az --delete -e "ssh -F $REPO_DIR/$SSH_CONFIG" \
    --exclude node_modules --exclude .direnv --exclude stack/.cache \
    --exclude out --exclude test-results --exclude playwright-report \
    --exclude 'stack/.env*' --exclude stack/certs --exclude stack/keys --exclude awskeys.txt \
    "$REPO_DIR/" "$1:~/gpp-tests/"
}

# owned_or_die ID... — refuse to touch an instance this wizard did not launch. The tag and
# the Name are both re-read from AWS, so a stale id in $ENV_FILE cannot point the lifecycle
# calls at someone else's Department=Software instance.
owned_or_die() {
  local id tag name
  for id in "$@"; do
    tag="$(awsx ec2 describe-instances --instance-ids "$id" \
      --query "Reservations[0].Instances[0].Tags[?Key=='$TAG_KEY']|[0].Value" --output text 2>/dev/null || true)"
    name="$(awsx ec2 describe-instances --instance-ids "$id" \
      --query "Reservations[0].Instances[0].Tags[?Key=='Name']|[0].Value" --output text 2>/dev/null || true)"
    if [[ "$tag" != "$TAG_VALUE" || " $NAMES_WE_LAUNCH " != *" $name "* ]]; then
      warn "refusing to touch $id: it is not an instance this wizard launched ($TAG_KEY=$tag, Name=$name)"
      exit 1
    fi
  done
}

# follow_k6 ID LOG — follow a detached k6 run on the generator until the k6 process is gone.
# The tail runs over SSM, and a laptop that sleeps drops that session: the first version
# took the dropped tail for "run finished" and went on to collect and stop the pair while k6
# was still running. So the tail is only the live view; the end of the run is decided by
# polling for the process over fresh sessions, each retried until the laptop is back.
follow_k6() {
  local id="$1" log="$2" alive
  ssh_to "$id" "tail -f --pid=\$(pgrep -x k6 | head -1) $log" || true
  while :; do
    alive="$(ssh_to "$id" "pgrep -x k6 | head -1" 2>/dev/null)" && [[ -z "$alive" ]] && break
    [[ -n "$alive" ]] && note "k6 still running on $id (pid $alive); checking again in 30 s" \
      || note "cannot reach $id right now; retrying in 30 s"
    sleep 30
  done
  # The tail may have missed the end of the log while the session was down.
  ssh_to "$id" "tail -n 40 $log" 2>/dev/null || true
}

# wait_for_ssm ID — the agent registers ~20s after the instance runs; ssh needs it Online.
wait_for_ssm() {
  local id="$1" status=""
  for _ in $(seq 1 60); do
    status="$(awsx ssm describe-instance-information --filters "Key=InstanceIds,Values=$id" \
      --query 'InstanceInformationList[0].PingStatus' --output text 2>/dev/null || true)"
    [[ "$status" == "Online" ]] && return 0
    sleep 5
  done
  warn "$id never came Online in SSM (last status: $status)"
  exit 1
}

# ── AUTO mode ─────────────────────────────────────────────────────────────
# AUTO=1 runs the whole thing unattended: no prompt waits, every answer comes from the
# environment, and the run is logged to out/. This is the body of the workflow-driven run
# ticket 016 is waiting on; until IT grants CI an identity it starts from a laptop.
#
#   AUTO=1 RUN_EXECUTION=1 RUN_LOAD=0 TEARDOWN=stop loadtest/aws-first-run.sh
#
#   RUN_EXECUTION / RUN_LOAD        y|1|true runs that stage; unset skips it
#   TEARDOWN                        stop (default) | terminate | leave
#   CONTINUE_WITHOUT_GRAFANA        default y: a rejected push does not end the run
#   CONTINUE_AFTER_FAILURE          default n: a red regression suite ends the run
#   EXEC_MINUTES, OBSERVE_INSTANCES, STEP_SECONDS_MIN/MAX, EXECUTION_OBSERVATIONS as in stage 8
#   RUN_SUBSCRIBERS, SUBSCRIBERS, CHURN_VUS, SUBSCRIBER_MINUTES, SESSION_SECONDS as in stage 9
#   HEROKU_API_KEY                  required (the repo's .env, loaded by direnv, is the place)
#   any `ask` value (AWS_PROFILE, TARGET_TYPE, …) by the same name; else the saved value
#
# A failure must not leave two instances billing until the safety stop when nobody is
# watching, so any non-zero exit stops the pair unless TEARDOWN=leave.
if [[ -n "${AUTO:-}" ]]; then
  AUTO_LOG="out/aws-run-$(date -u +%Y%m%dT%H%M%SZ).log"
  exec > >(tee -a "$AUTO_LOG") 2>&1
  [[ -n "${HEROKU_API_KEY:-}" ]] || { warn "AUTO needs HEROKU_API_KEY in the environment"; exit 1; }
  auto_cleanup() {
    local rc=$?
    [[ $rc -ne 0 ]] || return 0
    if [[ -n "${TARGET_ID:-}" && -n "${GEN_ID:-}" && "${TEARDOWN:-stop}" != "leave" ]]; then
      warn "AUTO: exiting with status $rc — stopping $TARGET_ID and $GEN_ID"
      if owned_or_die "$TARGET_ID" "$GEN_ID"; then
        awsx ec2 stop-instances --instance-ids "$TARGET_ID" "$GEN_ID" >/dev/null && say "both stopping"
      fi
    fi
    if [[ -n "${S3_BUCKET:-}" && -n "${S3_PREFIX:-}" && -z "${KEEP_ATTACHMENTS:-}" ]]; then
      awsx s3 rm --recursive --quiet "s3://$S3_BUCKET/$S3_PREFIX/" >/dev/null 2>&1 \
        && say "AUTO: deleted this run's attachments under s3://$S3_BUCKET/$S3_PREFIX"
    fi
    note "AUTO: log at $AUTO_LOG"
  }
  trap auto_cleanup EXIT
  trap 'exit 130' INT TERM
  say "AUTO mode: no prompts; everything below is also in $AUTO_LOG"
fi

banner "GPP load test on AWS — NOIRLab us-west-2"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Preflight — the AWS identity you are about to spend money with"
say "This wizard launches two EC2 instances through NOIRLab's GPP launch template,"
say "runs the k6 regression and load suites against them, and stops them again."
say "Roughly \$1.16 per hour while both run."
printf '\n'

command -v aws >/dev/null 2>&1 || { warn "the AWS CLI is not installed — https://aws.amazon.com/cli/"; exit 1; }
command -v rsync >/dev/null 2>&1 || { warn "rsync is required (it ships with macOS)"; exit 1; }
command -v session-manager-plugin >/dev/null 2>&1 || {
  warn "the AWS Session Manager plugin is not installed — all access goes through SSM"
  step "brew install --cask session-manager-plugin"
  exit 1
}

ask AWS_REGION  "AWS region [us-west-2]:"
[[ -n "$AWS_REGION" ]] || AWS_REGION="us-west-2"
ask AWS_PROFILE "AWS CLI profile [gpp-tests]:"
[[ -n "$AWS_PROFILE" ]] || AWS_PROFILE="gpp-tests"

CALLER_ARN="$(awsx sts get-caller-identity --query Arn --output text 2>/dev/null || true)"
if [[ -z "$CALLER_ARN" ]]; then
  warn "could not call sts:GetCallerIdentity — check your credentials for this profile"
  exit 1
fi
ACCOUNT_ID="$(awsx sts get-caller-identity --query Account --output text)"
say ""
say "account:  $ACCOUNT_ID"
say "identity: $CALLER_ARN"
say ""

# Root cannot be constrained by IAM, and the launch procedure is IAM. Refuse rather than warn.
if [[ "$CALLER_ARN" == *":root" ]]; then
  warn "That is the account ROOT user — use your own IAM user's profile."
  exit 1
fi

warn "This account is SHARED (EKS clusters, databases, other teams' instances)."
note "  This wizard launches only through the GPP launch template, and only ever"
note "  starts, stops or terminates instances it launched and tagged $TAG_KEY=$TAG_VALUE."
write_env AWS_REGION "$AWS_REGION"
write_env AWS_PROFILE "$AWS_PROFILE"

# The object store (ticket 028): the stack on the target writes proposal attachments to the
# real bucket through its re-signing proxy, under a prefix of this run's own, which the
# teardown stage deletes. The proxy uses the instance role; this check only confirms the
# bucket is visible from here, which is what the cleanup needs.
S3_BUCKET="${S3_BUCKET:-noirlab-gpp-tests}"
S3_PREFIX="gpp-tests/aws-$(date -u +%Y%m%dT%H%M%SZ)"
if awsx s3api head-bucket --bucket "$S3_BUCKET" >/dev/null 2>&1; then
  say "bucket:   s3://$S3_BUCKET/$S3_PREFIX  (this run's attachments; deleted at teardown)"
else
  warn "cannot see s3://$S3_BUCKET from this profile — the stack will use its own object store (S3_MODE=local)"
  S3_BUCKET=""
fi
pause

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Launch template and key pair"
say "The template carries the network, security groups and instance profile the"
say "procedure requires; the key pair is only for ssh tunnelled through SSM."
printf '\n'

ask LAUNCH_TEMPLATE "Launch template name [NOIRLab-Software-GPP]:"
[[ -n "$LAUNCH_TEMPLATE" ]] || LAUNCH_TEMPLATE="NOIRLab-Software-GPP"
TEMPLATE_SUMMARY="$(awsx ec2 describe-launch-template-versions --launch-template-name "$LAUNCH_TEMPLATE" \
  --versions '$Default' --query 'LaunchTemplateVersions[0].LaunchTemplateData.[NetworkInterfaces[0].SubnetId,IamInstanceProfile.Name,join(`,`,NetworkInterfaces[0].Groups)]' \
  --output text 2>/dev/null || true)"
[[ -n "$TEMPLATE_SUMMARY" ]] || { warn "launch template $LAUNCH_TEMPLATE not found in $AWS_REGION"; exit 1; }
read -r SUBNET_ID PROFILE_NAME SG_IDS <<<"$TEMPLATE_SUMMARY"
say "template $LAUNCH_TEMPLATE: subnet $SUBNET_ID, profile $PROFILE_NAME"
note "  security groups $SG_IDS"
write_env LAUNCH_TEMPLATE "$LAUNCH_TEMPLATE"

ask KEY_NAME "EC2 key pair name [gpp-tests-loadtest]:"
[[ -n "$KEY_NAME" ]] || KEY_NAME="gpp-tests-loadtest"
PEM_PATH="$HOME/.ssh/$KEY_NAME.pem"

if awsx ec2 describe-key-pairs --key-names "$KEY_NAME" >/dev/null 2>&1; then
  say "key pair $KEY_NAME already exists in $AWS_REGION"
  [[ -f "$PEM_PATH" ]] || { warn "but $PEM_PATH is missing — pick another name, or delete the key pair in EC2"; exit 1; }
else
  # Never overwrite a private key: a same-named .pem belongs to a key pair elsewhere.
  [[ ! -e "$PEM_PATH" ]] || { warn "$PEM_PATH already exists but is not a key pair in $AWS_REGION — pick another name"; exit 1; }
  awsx ec2 create-key-pair --key-name "$KEY_NAME" \
    --query KeyMaterial --output text > "$PEM_PATH"
  chmod 600 "$PEM_PATH"
  say "created $KEY_NAME → $PEM_PATH"
fi
write_env KEY_NAME "$KEY_NAME"
write_ssh_config
say "ssh over SSM configured in $SSH_CONFIG"
pause

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Launch the target and the generator"
warn "x86_64 only: the lucuma images are linux/amd64, so a Graviton instance"
note "  would be cheaper and then fail to run them. Keep the defaults unless you"
note "  are deliberately testing another size."
printf '\n'

ask TARGET_TYPE "Target instance type [m7i.4xlarge]:"
[[ -n "$TARGET_TYPE" ]] || TARGET_TYPE="m7i.4xlarge"
ask GEN_TYPE "Generator instance type [c7i.2xlarge]:"
[[ -n "$GEN_TYPE" ]] || GEN_TYPE="c7i.2xlarge"
ask MAX_HOURS "Safety stop after how many hours of uptime [8]:"
[[ -n "$MAX_HOURS" ]] || MAX_HOURS=8

# Canonical's image, found through ec2:DescribeImages — this user has no ssm:GetParameters.
AMI_ID="$(awsx ec2 describe-images --owners 099720109477 \
  --filters 'Name=name,Values=ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*' \
  --query 'sort_by(Images,&CreationDate)[-1].ImageId' --output text)"
say "Ubuntu 24.04 amd64 image: $AMI_ID"

# First boot only: stop (not terminate) after MAX_HOURS, so a forgotten pair stops billing
# for compute without losing its disks. A restarted pair does not re-arm it.
USER_DATA="$(printf '#!/bin/bash\nshutdown -P +%s\n' "$(( MAX_HOURS * 60 ))")"

launch() {
  local name="$1" type="$2" disk="$3" tags
  tags="{Key=Name,Value=$name},{Key=Department,Value=Software},{Key=Project,Value=GPP},{Key=$TAG_KEY,Value=$TAG_VALUE}"
  awsx ec2 run-instances \
    --launch-template "LaunchTemplateName=$LAUNCH_TEMPLATE" \
    --image-id "$AMI_ID" --instance-type "$type" --key-name "$KEY_NAME" --count 1 \
    --block-device-mappings "DeviceName=/dev/sda1,Ebs={VolumeSize=$disk,VolumeType=gp3,DeleteOnTermination=true}" \
    --instance-initiated-shutdown-behavior stop \
    --user-data "$USER_DATA" \
    --tag-specifications "ResourceType=instance,Tags=[$tags]" \
      "ResourceType=volume,Tags=[{Key=Department,Value=Software},{Key=Project,Value=GPP},{Key=$TAG_KEY,Value=$TAG_VALUE}]" \
    --query 'Instances[0].InstanceId' --output text
}

if [[ -z "$(_existing TARGET_ID || true)" ]]; then
  # The template's root disk is ~7 GB; the stack's images and database need far more.
  TARGET_ID="$(launch gpp-tests-target "$TARGET_TYPE" 60)"
  GEN_ID="$(launch gpp-tests-generator "$GEN_TYPE" 30)"
  write_env TARGET_ID "$TARGET_ID"
  write_env GEN_ID "$GEN_ID"
  say "launched target $TARGET_ID and generator $GEN_ID — waiting for them to run"
  awsx ec2 wait instance-running --instance-ids "$TARGET_ID" "$GEN_ID"
else
  TARGET_ID="$(_existing TARGET_ID)"; GEN_ID="$(_existing GEN_ID)"
  owned_or_die "$TARGET_ID" "$GEN_ID"
  say "reusing $TARGET_ID / $GEN_ID from a previous run"
  # A pair that the previous run has only just told to stop is still `stopping`, and AWS
  # refuses to start a stopping instance. The first version swallowed that refusal and then
  # waited ten minutes for "running" (2026-10-07, a rerun straight after a run). So: wait
  # for the stop to finish, start, and let a refused start be the error it is.
  states="$(awsx ec2 describe-instances --instance-ids "$TARGET_ID" "$GEN_ID" \
    --query 'Reservations[].Instances[].State.Name' --output text | tr '\t' ' ')"
  if [[ "$states" == *stopping* || "$states" == *shutting-down* ]]; then
    say "the pair is still stopping from the previous run ($states) — waiting for it to finish"
    awsx ec2 wait instance-stopped --instance-ids "$TARGET_ID" "$GEN_ID"
    states="stopped stopped"
  fi
  if [[ "$states" == *stopped* ]]; then
    awsx ec2 start-instances --instance-ids "$TARGET_ID" "$GEN_ID" >/dev/null \
      || { warn "AWS refused to start $TARGET_ID / $GEN_ID (states: $states)"; exit 1; }
  elif [[ "$states" != "running running" ]]; then
    warn "unexpected instance states for $TARGET_ID / $GEN_ID: $states"
    exit 1
  fi
  awsx ec2 wait instance-running --instance-ids "$TARGET_ID" "$GEN_ID"
fi

TARGET_PRIVATE_IP="$(awsx ec2 describe-instances --instance-ids "$TARGET_ID" \
  --query 'Reservations[0].Instances[0].PrivateIpAddress' --output text)"
write_env TARGET_PRIVATE_IP "$TARGET_PRIVATE_IP"
say "waiting for both to register with SSM"
wait_for_ssm "$TARGET_ID"
wait_for_ssm "$GEN_ID"
say "target $TARGET_ID (private $TARGET_PRIVATE_IP) · generator $GEN_ID — both Online in SSM"
warn "both are billing from now until stage 12 (or the ${MAX_HOURS}h safety stop)."
pause

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Bootstrap the stack on the target"
say "Docker, Node 22, then stack/scripts/bootstrap.sh — the same script the"
say "nightly regression run boots from empty. Pulling ~3.5 GB of images, so"
say "this is the long stage: 8-15 minutes."
printf '\n'

if [[ -n "${HEROKU_API_KEY:-}" ]]; then
  say "using HEROKU_API_KEY from your environment"
else
  say "The images live only in Heroku's registry, so the target needs a key that"
  say "can pull them (read on lucuma-*-dev is enough)."
  ask_secret HEROKU_API_KEY "Heroku API key:"
fi

say "waiting for ssh over SSM on $TARGET_ID"
for _ in $(seq 1 30); do
  ssh_to "$TARGET_ID" true >/dev/null 2>&1 && break
  sleep 10
done

say "installing prerequisites"
ssh_to "$TARGET_ID" bash -s <<'REMOTE'
set -euo pipefail
sudo apt-get update -qq
sudo apt-get install -y -qq docker.io docker-compose-v2 git curl gpg jq rsync >/dev/null
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - >/dev/null 2>&1
sudo apt-get install -y -qq nodejs >/dev/null
sudo usermod -aG docker ubuntu
REMOTE

say "syncing the working copy (not a clone — this tests the code you have)"
rsync_to "$TARGET_ID"

# stack/docker-compose.yml ships CI-sized memory limits — odb 2g, postgres 2g, itc 1g,
# obscalc 1g, sso 768m, caddy 256m, hasura 512m — because its day job is booting on a 2-core
# GitHub runner. Left alone on a load target they are what you measure, not the machine.
#
# The shares below come from the 2026-08-27 runs on a 64 GiB m7i.4xlarge, not from a guess:
#
#   at  200 VUs   odb 11.6G  itc 3.0G  obscalc 2.7G  postgres 1.9G  sso 1.2G
#   ramping 1500  odb 23.3G  itc 4.7G  obscalc 3.9G  postgres 2.1G  sso 1.3G  hasura 0.45G
#
# Two OOM kills taught the rest. Run 1 left odb at its 2g default and the kernel killed it 14
# minutes in at ~185 VUs. Run 3 raised every service *except the proxy* — and caddy died at
# its 256m default, taking the whole run with it, because a saturated backend leaves
# connections queued in the proxy and its memory grows with them. Sizing six of seven
# services is the same as sizing none.
#
# These are caps, not reservations: measured total usage was ~36 GiB, so the shares may
# safely sum past what the box could satisfy all at once.
TARGET_MIB="$(awsx ec2 describe-instance-types --instance-types "$TARGET_TYPE" \
  --query 'InstanceTypes[0].MemoryInfo.SizeInMiB' --output text)"
pct() { printf '%sm' "$(( TARGET_MIB * $1 / 100 ))"; }
# The odb's heap: 24 % of the box, 60 % of its container. Left to the image's launcher the heap
# would be the container minus 1 GiB with -Xms = -Xmx, and resident memory would climb to the
# limit over a long run as the JVM touches it all (2026-10-03: 4.6 → 15.5 GiB in 20 minutes),
# leaving native memory 1 GiB to live in. See research/odb-memory-growth-handoff.md.
ODB_HEAP_MIB=$(( TARGET_MIB * 24 / 100 ))
LIMITS="ODB_MEM_LIMIT=$(pct 40) ODB_JAVA_OPTS='-Xms${ODB_HEAP_MIB}m -Xmx${ODB_HEAP_MIB}m' ITC_MEM_LIMIT=$(pct 10) OBSCALC_MEM_LIMIT=$(pct 8) \
CADDY_MEM_LIMIT=$(pct 8) PG_MEM_LIMIT=$(pct 6) SSO_MEM_LIMIT=$(pct 4) \
HASURA_MEM_LIMIT=$(pct 2) PG_MAX_CONNECTIONS=400"
say "memory limits for ${TARGET_MIB}MiB:"
say "  odb $(pct 40) (heap ${ODB_HEAP_MIB}m)  itc $(pct 10)  obscalc $(pct 8)  caddy $(pct 8)  postgres $(pct 6)  sso $(pct 4)  hasura $(pct 2)"
note "  Caps rather than reservations. Override any of them in the environment; a target that"
note "  only serves k6 does not need hasura at all (it is Explore's preferences service)."

# Attachments go to the real bucket when the preflight could see it (S3_MODE=bucket boots
# the re-signing proxy, which signs with the instance role), else to the stack's own store.
S3_ENV="S3_MODE=local"
if [[ -n "$S3_BUCKET" ]]; then
  S3_ENV="S3_MODE=bucket S3_BUCKET=$S3_BUCKET S3_PREFIX=$S3_PREFIX S3_REGION=$AWS_REGION"
  say "attachments: s3://$S3_BUCKET/$S3_PREFIX through the proxy and the instance role"
fi

say "booting the stack"
ssh_to "$TARGET_ID" "HEROKU_API_KEY='$HEROKU_API_KEY' $LIMITS $S3_ENV bash -lc 'cd ~/gpp-tests && sg docker -c \"stack/scripts/bootstrap.sh\"'"
say ""
say "the stack is up, its readiness checks passed, and the standard users are fabricated"
pause

# ── Stage 5 ───────────────────────────────────────────────────────────────
stage "Prepare the generator"
say "k6 and Node, the same working copy, /etc/hosts pointing the stack's names at"
say "the target's private ip, and the fabricated PI copied from the target."
printf '\n'

say "waiting for ssh over SSM on $GEN_ID"
for _ in $(seq 1 30); do
  ssh_to "$GEN_ID" true >/dev/null 2>&1 && break
  sleep 10
done

ssh_to "$GEN_ID" bash -s <<'REMOTE'
set -euo pipefail
sudo apt-get update -qq
sudo apt-get install -y -qq curl ca-certificates git rsync >/dev/null
curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash - >/dev/null 2>&1
sudo apt-get install -y -qq nodejs >/dev/null

# k6 from its release tarball rather than the apt repo. The documented apt route imports
# the signing key with `sudo gpg --recv-keys`, which needs a root GPG home (`sudo gpg -k`
# first) and dirmngr — neither present on a minimal cloud image — and then depends on a
# keyserver being reachable. One binary has none of those failure modes.
if ! command -v k6 >/dev/null 2>&1; then
  TAG="$(curl -fsSL https://api.github.com/repos/grafana/k6/releases/latest \
    | sed -n 's/.*"tag_name": *"\([^"]*\)".*/\1/p' | head -1)"
  [ -n "$TAG" ] || { echo "could not resolve the latest k6 release from GitHub" >&2; exit 1; }
  ASSET="k6-${TAG}-linux-amd64"
  curl -fsSL "https://github.com/grafana/k6/releases/download/${TAG}/${ASSET}.tar.gz" \
    | sudo tar -xz -C /usr/local/bin --strip-components=1 "${ASSET}/k6"
fi
k6 version
REMOTE

rsync_to "$GEN_ID"

ssh_to "$GEN_ID" "sudo sed -i '/gpp-test.internal/d' /etc/hosts && \
  echo '$TARGET_PRIVATE_IP odb.gpp-test.internal sso.gpp-test.internal itc.gpp-test.internal explore.gpp-test.internal prefs.gpp-test.internal mail.gpp-test.internal' \
  | sudo tee -a /etc/hosts >/dev/null"
say "generator resolves the stack at $TARGET_PRIVATE_IP"

# The observing-modes scenario logs in as the fabricated PI (ticket 030), and the proposal
# loop and the subscribers draw one identity per VU from the pool beside it (ticket 017).
# Both files are streamed target → laptop → generator and never printed or written locally.
ssh_to "$TARGET_ID" "cat ~/gpp-tests/stack/.env.standard-users" \
  | ssh_to "$GEN_ID" "umask 077 && cat > ~/gpp-tests/stack/.env.standard-users"
ssh_to "$TARGET_ID" "cat ~/gpp-tests/stack/.env.standard-users.json" \
  | ssh_to "$GEN_ID" "umask 077 && cat > ~/gpp-tests/stack/.env.standard-users.json"
say "the fabricated PI, staff and the standard-user pool are on the generator"
pause

# ── Stage 6 ───────────────────────────────────────────────────────────────
stage "Smoke run — 10 VUs, about two minutes"
say "Proves the whole path before committing 40 minutes: guest auth, the"
say "GraphQL mix, TLS through Caddy, and the target-host guard accepting"
say "*.gpp-test.internal. A failure here is cheap."
printf '\n'

K6_ENV="SUITE=load \
ODB_GRAPHQL_URL=https://odb.gpp-test.internal/odb \
SSO_URL=https://sso.gpp-test.internal"

# Asked once, here, so the smoke, regression and load runs all stream. The credentials are
# proven from the generator with tools/verify-metrics.sh before anything relies on them:
# k6 only *logs* a rejected push and still exits 0, which is how the 2026-10-02 load run
# streamed 40 minutes of 401s to nowhere.
GRAFANA_ARGS=""
if [[ -n "${K6_PROMETHEUS_RW_SERVER_URL:-}" && -n "${K6_PROMETHEUS_RW_USERNAME:-}" \
      && -n "${K6_PROMETHEUS_RW_PASSWORD:-}" ]]; then
  # Set in the repo's gitignored .env (direnv loads it), so nothing is asked.
  say "using the Grafana remote-write credentials from your environment"
  GC_PROM_RW_URL="$K6_PROMETHEUS_RW_SERVER_URL"
  GC_PROM_INSTANCE_ID="$K6_PROMETHEUS_RW_USERNAME"
  GC_PROM_TOKEN="$K6_PROMETHEUS_RW_PASSWORD"
  STREAM=1
elif confirm "Stream metrics to Grafana Cloud?"; then
  note "  URL from grafana.com → stack → Prometheus → Details, ending in /api/prom/push;"
  note "  username = the numeric Instance ID; token = an Access Policy token (glc_…)"
  note "  with metrics:write — a glsa_ service-account token always gets a 401."
  note "  Put all three in the repo's .env as K6_PROMETHEUS_RW_* to skip these prompts."
  ask       GC_PROM_RW_URL      "Prometheus remote-write URL:"
  ask       GC_PROM_INSTANCE_ID "Instance ID (username):"
  ask_secret GC_PROM_TOKEN      "Access policy token:"
  write_env GC_PROM_RW_URL "$GC_PROM_RW_URL"
  write_env GC_PROM_INSTANCE_ID "$GC_PROM_INSTANCE_ID"
  STREAM=1
fi
# The credentials live in a file on the generator that every k6 command sources, and travel
# there on ssh's stdin: never on a command line, where `ps` shows them and where a quoting
# error makes bash echo them back in clear (which is how the 2026-10-03 run printed the
# token). The file always exists, empty when not streaming, so the commands never branch.
grafana_file() {
  ssh_to "$GEN_ID" "umask 077 && mkdir -p ~/gpp-tests/out && cat > ~/gpp-tests/out/grafana.env"
}
: | grafana_file
if [[ -n "${STREAM:-}" ]]; then
  printf 'export K6_PROMETHEUS_RW_SERVER_URL=%q\nexport K6_PROMETHEUS_RW_USERNAME=%q\nexport K6_PROMETHEUS_RW_PASSWORD=%q\nexport K6_PROMETHEUS_RW_TREND_STATS=%q\n' \
    "$GC_PROM_RW_URL" "$GC_PROM_INSTANCE_ID" "$GC_PROM_TOKEN" "avg,p(95),p(99)" | grafana_file
  say "checking the credentials with a five-second push"
  if ssh_to "$GEN_ID" "cd ~/gpp-tests && . out/grafana.env && tools/verify-metrics.sh"; then
    GRAFANA_ARGS="-o experimental-prometheus-rw"
    say "Grafana accepted the push — the runs below stream live"
  else
    warn "Grafana rejected the credentials (see above); the runs below will not stream"
    : | grafana_file
    confirm "Carry on without Grafana?" CONTINUE_WITHOUT_GRAFANA y || { say "Stopping here — nothing torn down."; exit 1; }
  fi
fi

ssh_to "$GEN_ID" "cd ~/gpp-tests && . out/grafana.env && $K6_ENV \
  VUS_LOW=5 VUS_HIGH=10 STAGE_1=30s STAGE_2=30s STAGE_3=30s STAGE_4=10s \
  MIN_CHECK_RATE=0.95 k6 run $GRAFANA_ARGS k6/load.js" || {
    warn "the smoke run failed — fix this before going further"
    note "  aws --region $AWS_REGION --profile $AWS_PROFILE ssm start-session --target $GEN_ID"
    note "  aws --region $AWS_REGION --profile $AWS_PROFILE ssm start-session --target $TARGET_ID"
    note "    then: cd ~ubuntu/gpp-tests && sudo docker compose -f stack/docker-compose.yml logs odb"
    exit 1
  }
say ""
say "plumbing confirmed"
pause

# ── Stage 7 ───────────────────────────────────────────────────────────────
stage "Regression suite — every v1 scenario plus every observing mode"
say "k6/regression.js, as the nightly runs it: the guest scenarios, then one"
say "observation per observing mode as the fabricated PI (ticket 030). A few minutes."
printf '\n'

# The execution VU (ticket 021) impersonates Observe with the stack's service JWT, which
# bootstrap wrote on the target. Streamed target → laptop → generator like the PI file.
ssh_to "$TARGET_ID" "grep '^export ODB_SERVICE_JWT=' ~/gpp-tests/stack/.env.generated" \
  | ssh_to "$GEN_ID" "umask 077 && cat > ~/gpp-tests/stack/.env.service"
say "the service JWT is on the generator"

# Output goes to a file first and is printed after: a `| tee` would report tee's exit code,
# and the remote shell is dash, which has no pipefail.
if ssh_to "$GEN_ID" "cd ~/gpp-tests && mkdir -p out && set -a && . stack/.env.standard-users && . stack/.env.service && set +a && . out/grafana.env && \
  SUITE=regression k6 run $GRAFANA_ARGS --summary-export out/k6-regression-summary.json k6/regression.js \
  > out/k6-regression.log 2>&1; rc=\$?; cat out/k6-regression.log; exit \$rc"; then
  say ""
  say "regression green on AWS"
else
  warn "the regression suite failed — its log is collected in stage 11"
  confirm "Carry on to the load profile anyway?" CONTINUE_AFTER_FAILURE n || { say "Stopping here — nothing torn down."; exit 1; }
fi
pause

# ── Stage 8 ───────────────────────────────────────────────────────────────
stage "Observe execution — Observe instances executing sequences, ~20 minutes"
say "k6/execution.js (ticket 021): each VU is one Observe server instance on the"
say "service JWT, executing seeded GMOS observations at a compressed cadence and"
say "reporting the step ODB overhead. The odb's container memory is sampled on the"
say "target throughout: locally it climbed to its limit under this traffic, and"
say "this run is what settles whether that was emulation or the odb."
printf '\n'

RAN_EXEC=""
EXEC_MINUTES="${EXEC_MINUTES:-20}"
EXEC_INSTANCES="${OBSERVE_INSTANCES:-2}"
note "Enter skips this stage (the prompt is y/N) — type y to run it."
if confirm "Run the execution profile now ($EXEC_INSTANCES instances, $EXEC_MINUTES minutes)?" RUN_EXECUTION n; then
  say "re-arming the safety stop on both instances: $((EXEC_MINUTES + 60)) minutes from now"
  for id in "$TARGET_ID" "$GEN_ID"; do
    ssh_to "$id" "sudo shutdown -c 2>/dev/null; sudo shutdown -P +$((EXEC_MINUTES + 60))" >/dev/null 2>&1 \
      || warn "could not re-arm the safety stop on $id — watch its uptime"
  done

  # Container memory and CPU every 30 s for the run's length plus a margin, detached on the
  # target, ending by its own clock. One line per sample: time, then name/mem/cpu per
  # container. `setsid -f` puts it in its own session: the first version (`nohup … &` under
  # `timeout`) kept the ssh session open until the sampler's timeout fired, so k6 started 24
  # minutes late and the samples covered the idle wait instead of the run (2026-10-03).
  SAMPLE_UNTIL="\$(( \$(date +%s) + $((EXEC_MINUTES * 60 + 240)) ))"
  ssh_to "$TARGET_ID" "mkdir -p ~/gpp-tests/out && setsid -f sh -c \
    'end=$SAMPLE_UNTIL; while [ \$(date +%s) -lt \$end ]; do echo \"\$(date -u +%FT%TZ) \$(sudo docker stats --no-stream --format \"{{.Name}} {{.MemUsage}} {{.CPUPerc}}\" | tr \"\\n\" \";\")\"; sleep 30; done' \
    < /dev/null > ~/gpp-tests/out/odb-stats.log 2>&1; sleep 1" \
    || warn "could not start the memory sampler on the target"
  say "sampling container memory on the target every 30 s (started $(date -u +%H:%M:%SZ))"

  # Detached like the load profile; the service JWT is read on the generator from the file
  # streamed in stage 7, never passed on a command line.
  # The ssh exit status is pgrep's: k6 must be alive five seconds in, or the start failed
  # (the 2026-10-03 run lost its stage to a quoting error that `|| true` swallowed).
  if ssh_to "$GEN_ID" "cd ~/gpp-tests && mkdir -p out && \
    nohup sh -c '. stack/.env.service; . out/grafana.env; exec env $K6_ENV OTEL_ENVIRONMENT=aws-loadtest \
    OBSERVE_INSTANCES=$EXEC_INSTANCES STEP_SECONDS_MIN=${STEP_SECONDS_MIN:-5} STEP_SECONDS_MAX=${STEP_SECONDS_MAX:-10} \
    DURATION=${EXEC_MINUTES}m EXECUTION_OBSERVATIONS=${EXECUTION_OBSERVATIONS:-4} \
    k6 run $GRAFANA_ARGS --summary-trend-stats avg,min,med,max,p\(90\),p\(95\),p\(99\) \
    --summary-export out/k6-execution-summary.json k6/execution.js' \
    < /dev/null > out/k6-execution.log 2>&1 & sleep 5; pgrep -x k6 >/dev/null"; then
    say "running detached on the generator since $(date -u +%H:%M:%SZ); following the log."
    note "Ctrl-C stops the tail, not the run. Re-attach with:"
    note "  aws --region $AWS_REGION --profile $AWS_PROFILE ssm start-session --target $GEN_ID"
    note "    then: tail -f ~ubuntu/gpp-tests/out/k6-execution.log"
    printf '\n'
    follow_k6 "$GEN_ID" gpp-tests/out/k6-execution.log
  else
    warn "k6 did not start on the generator — the end of its log:"
    ssh_to "$GEN_ID" "tail -n 20 gpp-tests/out/k6-execution.log" || true
  fi
  RAN_EXEC=1
  pause "Run finished — press Enter to continue"
else
  say "skipped the execution profile"
fi

# ── Stage 9 ───────────────────────────────────────────────────────────────
stage "Subscribers — live websockets held by PIs and staff, with churn"
say "k6/subscribers.js (ticket 022): a steady population of Explore-tab and"
say "Observe-browser subscribers on graphql-transport-ws, plus sessions that come"
say "and go. Measures the round trip from an edit's HTTP ack to the event on the"
say "same socket, ping latency, drops and reconnects. The odb is sampled again."
printf '\n'

RAN_SUBS=""
SUB_MINUTES="${SUBSCRIBER_MINUTES:-10}"
SUB_STEADY="${SUBSCRIBERS:-50}"
SUB_CHURN="${CHURN_VUS:-10}"
note "Enter skips this stage (the prompt is y/N) — type y to run it."
if confirm "Run the subscribers profile now ($SUB_STEADY steady + $SUB_CHURN churning, $SUB_MINUTES minutes)?" RUN_SUBSCRIBERS n; then
  say "re-arming the safety stop on both instances: $((SUB_MINUTES + 60)) minutes from now"
  for id in "$TARGET_ID" "$GEN_ID"; do
    ssh_to "$id" "sudo shutdown -c 2>/dev/null; sudo shutdown -P +$((SUB_MINUTES + 60))" >/dev/null 2>&1 \
      || warn "could not re-arm the safety stop on $id — watch its uptime"
  done

  SAMPLE_UNTIL="\$(( \$(date +%s) + $((SUB_MINUTES * 60 + 240)) ))"
  ssh_to "$TARGET_ID" "mkdir -p ~/gpp-tests/out && setsid -f sh -c \
    'end=$SAMPLE_UNTIL; while [ \$(date +%s) -lt \$end ]; do echo \"\$(date -u +%FT%TZ) \$(sudo docker stats --no-stream --format \"{{.Name}} {{.MemUsage}} {{.CPUPerc}}\" | tr \"\\n\" \";\")\"; sleep 30; done' \
    < /dev/null > ~/gpp-tests/out/odb-stats-subscribers.log 2>&1; sleep 1" \
    || warn "could not start the memory sampler on the target"
  say "sampling container memory on the target every 30 s (started $(date -u +%H:%M:%SZ))"

  # The churn executor's ramp/hold/drain follow the stage length: one minute up, the rest
  # held, two minutes draining. Subscribers log in as the fabricated PI and staff users.
  SUB_HOLD=$(( SUB_MINUTES > 3 ? SUB_MINUTES - 3 : 1 ))
  if ssh_to "$GEN_ID" "cd ~/gpp-tests && mkdir -p out && \
    nohup sh -c '. stack/.env.standard-users; . out/grafana.env; exec env $K6_ENV OTEL_ENVIRONMENT=aws-loadtest \
    SUBSCRIBERS=$SUB_STEADY CHURN_VUS=$SUB_CHURN DURATION=${SUB_MINUTES}m \
    SESSION_SECONDS=${SESSION_SECONDS:-120} CHURN_RAMP=1m CHURN_HOLD=${SUB_HOLD}m CHURN_DRAIN=2m \
    k6 run $GRAFANA_ARGS --summary-trend-stats avg,min,med,max,p\(90\),p\(95\),p\(99\) \
    --summary-export out/k6-subscribers-summary.json k6/subscribers.js' \
    < /dev/null > out/k6-subscribers.log 2>&1 & sleep 5; pgrep -x k6 >/dev/null"; then
    say "running detached on the generator since $(date -u +%H:%M:%SZ); following the log."
    note "Ctrl-C stops the tail, not the run. Re-attach with:"
    note "  aws --region $AWS_REGION --profile $AWS_PROFILE ssm start-session --target $GEN_ID"
    note "    then: tail -f ~ubuntu/gpp-tests/out/k6-subscribers.log"
    printf '\n'
    follow_k6 "$GEN_ID" gpp-tests/out/k6-subscribers.log
  else
    warn "k6 did not start on the generator — the end of its log:"
    ssh_to "$GEN_ID" "tail -n 20 gpp-tests/out/k6-subscribers.log" || true
  fi
  RAN_SUBS=1
  pause "Run finished — press Enter to continue"
else
  say "skipped the subscribers profile"
fi

# ── Stage 10 ──────────────────────────────────────────────────────────────
stage "The full load profile — 0→50→200 VUs, ~40 minutes"
say "OTEL_ENVIRONMENT=aws-loadtest tags the summary as its own environment, so"
say "these numbers never blend into a Heroku baseline."
printf '\n'

RAN_LOAD=""
if confirm "Run the 40-minute load profile now?" RUN_LOAD n; then
  # The first-boot safety stop (stage 3) counts from launch, not from this stage. On
  # 2026-10-02 a 3-hour stop was minutes from firing 17 minutes into the profile — so push it
  # out to 90 minutes from now on both instances (load profile + collect + teardown).
  say "re-arming the safety stop on both instances: 90 minutes from now"
  for id in "$TARGET_ID" "$GEN_ID"; do
    ssh_to "$id" "sudo shutdown -c 2>/dev/null; sudo shutdown -P +90" >/dev/null 2>&1 \
      || warn "could not re-arm the safety stop on $id — watch its uptime"
  done

  # Grafana was settled (and verified) at the smoke stage.
  # Detached, so a dropped SSM session or a sleeping laptop cannot lose the run. stdin must
  # come from /dev/null too: a background job still holding the session's stdin keeps ssh
  # open until k6 exits, which froze the wizard here for the whole 40 minutes (2026-10-02).
  if ssh_to "$GEN_ID" "cd ~/gpp-tests && mkdir -p out && \
    nohup sh -c '. out/grafana.env; exec env $K6_ENV OTEL_ENVIRONMENT=aws-loadtest \
    k6 run $GRAFANA_ARGS --summary-export out/k6-summary.json k6/load.js' \
    < /dev/null > out/k6-run.log 2>&1 & sleep 5; pgrep -x k6 >/dev/null"; then
    say "running detached on the generator; following the log."
    note "Ctrl-C stops the tail, not the run. Re-attach with:"
    note "  aws --region $AWS_REGION --profile $AWS_PROFILE ssm start-session --target $GEN_ID"
    note "    then: tail -f ~ubuntu/gpp-tests/out/k6-run.log"
    printf '\n'
    # `pgrep -x k6` matches the k6 binary only. The earlier `pgrep -f 'k6 run'` also matched
    # this very shell (its command line contains the pattern), so tail waited on itself and
    # never returned after the run ended (2026-10-02).
    follow_k6 "$GEN_ID" gpp-tests/out/k6-run.log
  else
    warn "k6 did not start on the generator — the end of its log:"
    ssh_to "$GEN_ID" "tail -n 20 gpp-tests/out/k6-run.log" || true
  fi
  RAN_LOAD=1
  pause "Run finished — press Enter to collect the results"
else
  say "skipped the load profile"
fi

# ── Stage 11 ──────────────────────────────────────────────────────────────
stage "Collect the numbers"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
scp_from "$GEN_ID" "gpp-tests/out/k6-regression-summary.json" "out/k6-aws-regression-$STAMP.json" 2>/dev/null \
  && say "saved out/k6-aws-regression-$STAMP.json" || warn "no regression summary to collect"
scp_from "$GEN_ID" "gpp-tests/out/k6-regression.log" "out/k6-aws-regression-$STAMP.log" 2>/dev/null || true

if [[ -n "$S3_BUCKET" ]]; then
  # What the run uploaded: the count and bytes are the surge model's attachment leg (017).
  say "attachments under s3://$S3_BUCKET/$S3_PREFIX:"
  awsx s3 ls --recursive --summarize "s3://$S3_BUCKET/$S3_PREFIX/" 2>/dev/null \
    | grep -E 'Total (Objects|Size)' | sed 's/^ */    /' || say "    none"
fi

if [[ -n "$RAN_EXEC" ]]; then
  scp_from "$GEN_ID" "gpp-tests/out/k6-execution-summary.json" "out/k6-aws-execution-$STAMP.json" 2>/dev/null \
    && say "saved out/k6-aws-execution-$STAMP.json" || warn "no execution summary to collect"
  scp_from "$GEN_ID" "gpp-tests/out/k6-execution.log" "out/k6-aws-execution-$STAMP.log" 2>/dev/null || true
  scp_from "$TARGET_ID" "gpp-tests/out/odb-stats.log" "out/odb-stats-aws-$STAMP.log" 2>/dev/null \
    && say "saved out/odb-stats-aws-$STAMP.log" || warn "no memory samples to collect"
  printf '\n'

  [[ -f "out/k6-aws-execution-$STAMP.json" ]] && node --input-type=commonjs -e '
  const fs = require("fs");
  const s = require("./out/k6-aws-execution-'"$STAMP"'.json");
  const m = s.metrics ?? {};
  const p = (k, q) => m[k]?.[q]?.toFixed(0) ?? "—";
  console.log("  steps executed     :", m.gpp_execution_steps?.count ?? "—");
  console.log("  step overhead      : p95", p("odb_step_overhead", "p(95)"), "ms · p99", p("odb_step_overhead", "p(99)"), "ms");
  for (const point of ["RecordVisit", "StepRecorded", "RecordDataset", "Flush", "ExecutionConfig"]) {
    console.log("    " + point.padEnd(17) + ": p95", p("odb_step_wait{operation:" + point + "}", "p(95)"), "ms");
  }
  console.log("  checks             :", ((m.checks?.value ?? 0) * 100).toFixed(2) + "%");
  console.log("  graphql errors     :", m.odb_graphql_errors?.count ?? 0);
  try {
    const lines = fs.readFileSync("./out/odb-stats-aws-'"$STAMP"'.log", "utf8").trim().split("\n");
    const odb = lines.map((l) => l.split(";").find((c) => c.includes("odb-1")) ?? "").map((c) => c.trim().split(" ")[1]).filter(Boolean);
    if (odb.length) console.log("  odb memory         : first", odb[0], "· last", odb[odb.length - 1], "· samples", odb.length);
  } catch (_e) { console.log("  odb memory         : no samples"); }
  ' || warn "could not summarise the execution run — the raw JSON is in out/"
  printf '\n'
  note "A flat odb memory line closes the ticket 021 watch item; a steady climb is a"
  note "finding for the odb team before any surge run. The samples are in the stats log."
fi

if [[ -n "$RAN_SUBS" ]]; then
  scp_from "$GEN_ID" "gpp-tests/out/k6-subscribers-summary.json" "out/k6-aws-subscribers-$STAMP.json" 2>/dev/null \
    && say "saved out/k6-aws-subscribers-$STAMP.json" || warn "no subscribers summary to collect"
  scp_from "$GEN_ID" "gpp-tests/out/k6-subscribers.log" "out/k6-aws-subscribers-$STAMP.log" 2>/dev/null || true
  scp_from "$TARGET_ID" "gpp-tests/out/odb-stats-subscribers.log" "out/odb-stats-subscribers-aws-$STAMP.log" 2>/dev/null \
    && say "saved out/odb-stats-subscribers-aws-$STAMP.log" || warn "no memory samples to collect"
  printf '\n'

  [[ -f "out/k6-aws-subscribers-$STAMP.json" ]] && node --input-type=commonjs -e '
  const fs = require("fs");
  const s = require("./out/k6-aws-subscribers-'"$STAMP"'.json");
  const m = s.metrics ?? {};
  const p = (k, q) => m[k]?.[q]?.toFixed(0) ?? "—";
  const c = (k) => m[k]?.count ?? 0;
  console.log("  sockets opened     :", c("odb_ws_connections"), "· reconnects", c("odb_ws_reconnects"), "· unanswered pings", c("odb_ws_unanswered_pings"), "· lost events", c("odb_ws_lost_events"));
  console.log("  ping               : explore-tab p95", p("odb_ws_ping{scenario:explore-tab}", "p(95)"), "ms · observe-browser p95", p("odb_ws_ping{scenario:observe-browser}", "p(95)"), "ms");
  console.log("  round trip (ack→event) : Explore p95", p("odb_ws_round_trip{operation:ProgramObservationsDelta}", "p(95)"), "ms · Observe p95", p("odb_ws_round_trip{operation:ObservationEdits}", "p(95)"), "ms");
  console.log("  event latency (send→event): Explore p95", p("odb_ws_event_latency{operation:ProgramObservationsDelta}", "p(95)"), "ms · Observe p95", p("odb_ws_event_latency{operation:ObservationEdits}", "p(95)"), "ms");
  console.log("  checks             :", ((m.checks?.value ?? 0) * 100).toFixed(2) + "%");
  console.log("  graphql errors     :", c("odb_graphql_errors"));
  try {
    const lines = fs.readFileSync("./out/odb-stats-subscribers-aws-'"$STAMP"'.log", "utf8").trim().split("\n");
    const odb = lines.map((l) => l.split(";").find((x) => x.includes("odb-1")) ?? "").map((x) => x.trim().split(" ")[1]).filter(Boolean);
    if (odb.length) console.log("  odb memory         : first", odb[0], "· last", odb[odb.length - 1], "· samples", odb.length);
  } catch (_e) { console.log("  odb memory         : no samples"); }
  ' || warn "could not summarise the subscribers run — the raw JSON is in out/"
  printf '\n'
fi

if [[ -n "$RAN_LOAD" ]]; then
  scp_from "$GEN_ID" "gpp-tests/out/k6-summary.json" "out/k6-aws-$STAMP.json" 2>/dev/null \
    && say "saved out/k6-aws-$STAMP.json" || warn "no load summary to collect"
  scp_from "$GEN_ID" "gpp-tests/out/k6-run.log" "out/k6-aws-$STAMP.log" 2>/dev/null || true
  printf '\n'

  [[ -f "out/k6-aws-$STAMP.json" ]] && node --input-type=commonjs -e '
  const s = require("./out/k6-aws-'"$STAMP"'.json");
  const m = s.metrics ?? {};
  const p95 = (k) => m[k]?.["p(95)"]?.toFixed(1) ?? "—";
  console.log("  target        : '"$TARGET_TYPE"' (generator '"$GEN_TYPE"')");
  console.log("  http p95      :", p95("http_req_duration"), "ms");
  console.log("  odb read  p95 :", p95("odb_read_duration"), "ms");
  console.log("  odb write p95 :", p95("odb_write_duration"), "ms");
  const failed = m.http_req_failed?.value;
  if (failed !== undefined) console.log("  request errors:", (failed * 100).toFixed(2) + "%");
  const pass = m.gpp_scenario_pass;
  if (pass) console.log("  scenario pass :", (pass.value * 100).toFixed(1) + "%");
  ' || warn "could not summarise — the raw JSON is in out/"

  printf '\n'
  note "No Heroku baseline exists yet (M4 unprovisioned), so this is an absolute"
  note "number on known hardware rather than a comparison. Keep the JSON: it is a"
  note "data point, and stage 3's instance types are what produced it."
fi
pause

# ── Stage 12 ──────────────────────────────────────────────────────────────
stage "Tear down — the stage that decides the bill"
owned_or_die "$TARGET_ID" "$GEN_ID"
warn "Two instances are still running: $TARGET_ID and $GEN_ID"
say ""
say "  stop      keeps the disks (a few \$/month), boots again in minutes"
say "  terminate leaves nothing behind at all"
say "  leave     they keep billing by the hour (until the ${MAX_HOURS}h safety stop)"
say ""
# This run's attachments are test junk in a shared bucket; delete them whatever happens to
# the instances. KEEP_ATTACHMENTS=1 keeps them for a look.
if [[ -n "${S3_BUCKET:-}" && -z "${KEEP_ATTACHMENTS:-}" ]]; then
  if awsx s3 rm --recursive --quiet "s3://$S3_BUCKET/$S3_PREFIX/" >/dev/null 2>&1; then
    say "deleted this run's attachments under s3://$S3_BUCKET/$S3_PREFIX"
  else
    warn "could not delete s3://$S3_BUCKET/$S3_PREFIX — remove it by hand"
  fi
fi

ask TEARDOWN "stop / terminate / leave [stop]:"
[[ -n "$TEARDOWN" ]] || TEARDOWN="stop"

case "$TEARDOWN" in
  terminate)
    if confirm "Terminate both instances? The stack and its data are gone for good." CONFIRM_TERMINATE y; then
      awsx ec2 terminate-instances --instance-ids "$TARGET_ID" "$GEN_ID" >/dev/null
      say "terminating. The key pair remains for next time."
      # Nothing to reuse, so drop the ids rather than offer them on a re-run.
      write_env TARGET_ID ""
      write_env GEN_ID ""
    else
      warn "left running — they are still billing"
    fi
    ;;
  leave)
    warn "left running — they are still billing"
    note "  aws ec2 stop-instances --instance-ids $TARGET_ID $GEN_ID --region $AWS_REGION --profile $AWS_PROFILE"
    ;;
  *)
    awsx ec2 stop-instances --instance-ids "$TARGET_ID" "$GEN_ID" >/dev/null
    say "stopping both. Re-run this wizard to bring the same pair back up."
    ;;
esac

finish
